### ISSUE TITLE
Home画面にDiscordへのリンクを追加する

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#100]
Figma:
https://www.figma.com/file/x71sECvdnsw8RTfKG0E4fB/FlutterKaigi-2023-App?type=design&node-id=54012-28023&mode=design&t=O7hayytZtUDgseYw-0

Link url:
https://discord.com/invite/Nr7H8JTJSF

**Comment by HironobuIga** [comment]
🙋‍♂️

**Comment by koji-1009** [comment]
@HironobuIga 
https://github.com/FlutterKaigi/conference-app-2023/issues/51 こちらアサインしましたので、対応終了後にアサインとさせてください！ もしも対応中に他の方から希望があがれば、そちらの方にアサインを先に振らせていただければと 🙏

**Comment by nitakan** [comment]
🙋

**Comment by koji-1009** [comment]
@nitakan 
Thanks!

@HironobuIga 
すいません、引き続きお願いします！
