### ISSUE TITLE
日本語環境において、プライバシーポリシーと行動規範へのリンクがhttpアクセスになっている

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#131]
**Describe the bug**
アプリ内の言語を日本語にした際、プライバシーポリシーと行動規範のリンクがhttpアクセスになっている

**Expected behavior**
アプリ内の言語を日本語にした際、プライバシーポリシーと行動規範のリンクがhttpsアクセスになっている

**Comment by nasustim** [comment]
🙋‍♂️

**Comment by koji-1009** [comment]
@nasustim 
Thanks!
