### ISSUE TITLE
Web版でテキストを選択しコピーなどができるようにする

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#135]
**Is your feature request related to a problem? Please describe.**
9月7日現在、Web版ではテキストの選択ができません。
イベント情報などをコピーできるように修正した方が良いと思われます。

**Describe the solution you'd like**
Flutterの機能を利用し、テキストを選択できるようにする。

**Describe alternatives you've considered**
none.

**Additional context**
* https://master-api.flutter.dev/flutter/material/SelectionArea-class.html

**Comment by takassh** [comment]
🙋

初めまして！
コードの公開ありがとうございます！参考になります！

こちら最初のコントリビュートとしてふさわしいかと感じましたので、コミットしてもよろしいでしょうか？

**Comment by koji-1009** [comment]
@takassh 
もちろんです！ アサインしますね！

**Comment by takassh** [comment]
@koji-1009 
こちらwebのみの対応でよろしいでしょうか？
`SelectionArea`を使う場合、すべてのプラットフォームで有効にした方が実装が綺麗になるので、特にこだわりがなければすべてのプラットフォームで有効にしても良いかなと感じました！

**Comment by koji-1009** [comment]
@takassh 
全てのプラットフォームで有効にしてしまって大丈夫です！
