### ISSUE TITLE
コントリビューター画面でdeveloperを表示中に画面をリロードするとstaff一覧が表示される

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#149]
**Describe the bug**
コントリビューター画面でdeveloperを表示中に画面をリロードするとstaff一覧が表示される

**To Reproduce**
1. Contributors画面を開く
2. Developer一覧を表示する
3. ブラウザ機能で画面をリロードする
4. Staff一覧画面になっている

**Expected behavior**
Developer一覧画面が表示されている。

**Screenshots**
none.

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Browser chrome
 - Version 116.0.5845.179

**Comment by trashfeed** [comment]
🙋‍♂️

**Comment by trashfeed** [comment]
issueについての質問です🙏

> Describe the bug
コントリビューター画面でdeveloperを表示中に画面をリロードするとstaff一覧が表示される

こちら↑ですが`main`ブランチで確認すると...

```diff
- コントリビューター画面で developer を表示中に画面をリロードするとstaff一覧が表示される
+ コントリビューター画面で staff を表示中に画面をリロードするとdeveloper一覧が表示される
```
という挙動のようでした。developer(開発者)表示時はリロード後もdeveloper(開発者)が表示されるので、期待値としては...

```
コントリビューター画面で staff を表示中に画面をリロードするとstaff一覧が表示される
```

でよろしいでしょうか 👀 

<img src=https://github.com/FlutterKaigi/conference-app-2023/assets/885696/f40e0070-c127-4219-a3ee-4042d765ee85  width=50%>


https://github.com/FlutterKaigi/conference-app-2023/assets/885696/9cf690c2-d90d-435a-9c6d-42c158c19730
