### ISSUE TITLE
セッション詳細画面にてGoogleカレンダー等外部カレンダーへの予定登録ができる導線を作る

### ISSUE THREAD

**Issue by Kurogoma4D** [FlutterKaigi/conference-app-2023#164]

**Comment by saito-tk** [comment]
こちら挑戦してみてもよろしいでしょうか？

**Comment by koji-1009** [comment]
@saito-tk はい! お願いいたします！
仕様について確認したいものがありましたら、こちらのIssueで投げていただければと。

**Comment by saito-tk** [comment]
@koji-1009 
ありがとうございます。
仕様ですが、Appbarのactionsへカレンダーもしくは共有アイコンを配置し、そこから
```
件名(title)：セッション名
詳細(description)：スピーカー名 & セッション説明？
場所(location)：部屋名？
日時(start,end)：開始時間と終了時間
```
の項目を設定する感じですかね？
issueタイトルが `Googleカレンダー等外部カレンダー` なので、ライブラリを導入して実装したほうが良いと思いました。
調べた結果
直近で更新が続いている「[add_2_calendar](https://pub.dev/packages/add_2_calendar)」が良いかなと思ったのですが、他に使ったほうがいいものやそもそもライブラリを使用しないほうがいいなどありますかね？
ちなみにadd_2_calendarはiOSの場合はリマインダーの設定がありますが、Androidの場合はなくユーザが手動で入力しないといけなさそうですね。

**Comment by Kurogoma4D** [comment]
@saito-tk 
AppBarのactionsに導線を作るイメージで大丈夫（現状Xへのリンクがあるので、`PopupMenuButton` を使って「共有」ボタンに置き換える）です！
共有方法ですが、 add_2_calendarだとAndroid/iOSにしか対応していないので他の手段があったほうがいいかなと思います。個人的には[Googleカレンダーのリンクを作る](https://webasterisk.sakura.ne.jp/googlecalendar_eventbuttonsgenerator/)のと、[ics形式](https://pub.dev/packages/ical)でダウンロードする方法を考えてました（Connpassのイベントページと同じ感じです）。
ただApple向けにicsファイルをダウンロードさせるだけだと直接予定を追加できなくて不便なので、結論Googleカレンダーへのリンク + iOS向けにadd_2_calendarの実装が一番良さそうです。

**Comment by saito-tk** [comment]
@koji-1009 @Kurogoma4D 
対応が遅れて申し訳ありません。
プルリクを作成しました！
https://github.com/FlutterKaigi/conference-app-2023/pull/250
