### ISSUE TITLE
スポンサー画面、Platinum・Gold・Silverの文字をcenter揃えにする

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#170]
**Describe the bug**
現在の実装では、左揃えになっている`Platinum`・`Gold`・`Silver`の文字を、左右中央揃えに変更する

**Expected behavior**
`Platinum`・`Gold`・`Silver`の文字が、左右中央揃えになっている

**Screenshots**
`Platinum`・`Gold`・`Silver`の文字が、marginを加味した上で左揃えになっている

**Comment by harusys** [comment]
🙋

**Comment by koji-1009** [comment]
@harusys 
Thanks!
