### ISSUE TITLE
ランチマップをソートできるようにする

### ISSUE THREAD

**Issue by koji-1009** [FlutterKaigi/conference-app-2023#183]
ランチマップにソート機能を追加する。標準の並び順と、徒歩時間のASC/DESCの切り替えられるようにする。

**Comment by HasegawaShuhei** [comment]
🙋‍♂️
初めまして！こちら担当させていただきたいのですが、よろしいでしょうか？

**Comment by koji-1009** [comment]
@HasegawaShuhei 
はい、お願いします！

**Comment by HasegawaShuhei** [comment]
ありがとうございます！

figmaに該当デザインがなかったのですが、ソート選択の表示について指定などありますでしょうか？
もしないのであれば、「所要時間（徒歩）」に[こちら](https://m3.material.io/components/menus/overview#b1704de4-94b7-4177-9e96-b677ae767cb4)のようなドロップダウンメニューを作ろうかと思うのですがいかがでしょうか？
<img src="https://github.com/FlutterKaigi/conference-app-2023/assets/77727737/0dcaf1bb-d05d-4921-b218-53252d7c8882" width="320">

**Comment by koji-1009** [comment]
@HasegawaShuhei 
はい、そちらでお願いします。
また一番左のセルに `id` の文字を追加して、初期状態では `id` でソートされている状態にしていただけますでしょうか。idと徒歩時間でソートが変更できるようにしたい、という趣旨です。

**Comment by HasegawaShuhei** [comment]
承知しました！

**Comment by HasegawaShuhei** [comment]
@koji-1009 
もうひとつ質問させていただきたいのですが、所要時間は全て単位が分で表示されるという想定で問題ないでしょうか？

**Comment by koji-1009** [comment]
@HasegawaShuhei 
> 所要時間は全て単位が分で表示されるという想定で問題ない
はい！ こちら問題ありません。

**Comment by HasegawaShuhei** [comment]
@koji-1009 
度々すみません🙏
RemoteConfigから送信されてくるStoreのデータにidが含まれていないのですが、データにidを含める予定などはありますでしょうか？

**Comment by koji-1009** [comment]
@HasegawaShuhei 
あ、そういえばindexでつけちゃってましたね。こちら、idカラムを追加しておきます！

**Comment by koji-1009** [comment]
@HasegawaShuhei 
idカラムを追加しました！
