### ISSUE TITLE
セッション詳細画面のお気に入りボタンを AppBar に置く

### ISSUE THREAD

**Issue by harusys** [FlutterKaigi/conference-app-2023#202]
**Is your feature request related to a problem? Please describe.**
セッション詳細画面に複数ボタンが置くと見通しが悪い

**Describe the solution you'd like**
セッション詳細画面のお気に入りボタン (IconButton) を、タイトル横から AppBar に変更する

**Additional context**
* [Material Design](https://m3.material.io/components/icon-buttons/guidelines#980e210b-2e69-48e9-8045-d8d432f43db5) を参考にする
* https://github.com/FlutterKaigi/conference-app-2023/pull/194#discussion_r1367739974 から起票

**Comment by harusys** [comment]
🙋 こちら対応します！

**Comment by koji-1009** [comment]
@harusys 
ありがとうございます！
