### ISSUE TITLE
PrimaryScrollController の設定

### ISSUE THREAD

**Issue by Zudah228** [FlutterKaigi/conference-app-2023#225]
Web の Issue から、手動で移行
https://github.com/FlutterKaigi/2023/issues/214

# Describe

iOS で画面の上をタップしたら、最上部にスクロールするアクションが実現できる。
## 参考
- [PrimaryScrollController](https://api.flutter.dev/flutter/widgets/PrimaryScrollController-class.html)
- [ScrollView.primary](https://api.flutter.dev/flutter/widgets/ScrollView/primary.html)

## `ScrollView.primary`
  - 「画面上部をタップした時にスクロールさせたい ScrollView」を指定できる。
  - `assert(!(controller != null && (primary ?? false)))` がある（`primary: true` の時は、`controller` を渡してはいけない）ので、`controller`を渡している場合は、工夫が必要。

## 新しい `PrimaryScrollController` でラップする。
  - `PrimaryScrollController` は `InheritedWidget` なので、サブツリーの振る舞いを変えられる。
  - 引数に `ScrollController` があるので、そこに使いたい `ScrollController` を渡す。
    - あとは、以下の2択
      - 上と同様、`ScrollView.primary` を true にする。
      - `PrimaryScrollController` と同じ `ScrollController` を、primary にしたい `ScrollView` に渡す。

# Screenshots

<video src="https://github.com/FlutterKaigi/2023/assets/62398366/dd853bef-259f-44da-bfdf-209be27176d4" width="320" />

# Environment

- Device: iPhone13
- OS: iOS 16.7.2
- Version: 1.1.0

**Comment by koji-1009** [comment]
https://github.com/flutter/flutter/issues/85603#issuecomment-876798161

**Comment by koji-1009** [comment]
対応しました！ PRの補足は下記記事に。
https://zenn.dev/koji_1009/articles/53962fc717c8ae
